### ISSUE TITLE
$s(triggerItem, "Y"); not being reflected in server session state.

### ISSUE THREAD

**Issue by scumdog** [rimblas/APEX-refresh-on-tab-focus#3]
The javascript function deferredUntil1stClick

sets the ITEM being used to defer the SQL loading from 'N' to 'Y' ie :-
                

>        // switch to visible the first time ONLY and refresh
>                         $s(triggerItem, "Y");

but this is never reflecred in the servers session state, and so the sql being run always sees a value of NVL(:ITEM_NAME, 'N')  being equal to N
I have had to change the code to 

>                         $s(triggerItem, "Y");
>                         apex.server.process(
>                             'Dummy Process to Set Session State'
>                             ,{pageItems: "#" + triggerItem}
>                             ,{dataType: "text"}
>                         );

to cause the server side session state to inherit the new ITEM value.

This is on Application Express 20.2.0.00.20, and causes the plugin to work for me.

I see one could say RTFM to me 
   "Use the item in your report and remember to add it to "Page Items to Submit"."
which I did  not see in your youtube explanation.

**Comment by rimblas** [comment]
@scumdog thanks, definitely worth adding to the readme.  Thank you for the feedback!
I would never use the ajax call to see the value. Really all you need is "Page Items to Submit"
